language: elixir

services:
  - postgresql

elixir:
  - 1.4
  - 1.5

otp_release:
  - 19.3

before_script:
  - mix compile
  - mix ecto.create
  - mix ecto.migrate

script:
  - ./cover.sh

env:
  global:
    - MIX_ENV=test
